# Generated by Django 5.0.7 on 2024-08-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type_team'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='teams',
            field=models.ManyToManyField(blank=True, to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
