# Generated by Django 5.0.7 on 2024-08-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_owner_alter_product_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('workspace', 'Workspace')], default='workspace', max_length=20),
        ),
    ]
