# Generated by Django 5.0.7 on 2024-08-30 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_board_product_alter_board_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(related_name='admin_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
    ]
