# Generated by Django 5.0.7 on 2024-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_list'),
        ('products', '0004_board_admins_board_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
