# Generated by Django 5.0.7 on 2024-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
