# Generated by Django 5.0.7 on 2024-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
