# Generated by Django 5.0.7 on 2024-09-03 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='cards.label'),
        ),
        migrations.AlterField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
