# Generated by Django 5.0.7 on 2024-09-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcommentitem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cards.card'),
        ),
    ]
